### ISSUE TITLE
校對語料的時，音檔袂使換

### ISSUE THREAD

**Issue by sih4sing5hong5** [i3thuan5/gi2_liau7_khoo3#30]
![2017-08-29 09-30-26](https://user-images.githubusercontent.com/5996555/29800443-c4165036-8c9c-11e7-9492-28c83f598453.png)
愛
1. 唯讀
抑是
2. 直接提掉

**Comment by a8568730** [comment]
django@2.1看來解決了 foreignkeys 無法限制唯讀的問題。

![2018-08-09 16-29-51](https://user-images.githubusercontent.com/6355592/43887444-7b620a0a-9bf1-11e8-8355-d190c9c58199.png)

django@2.1後，唯讀的外掛導致進去編輯頁的時候，發生500 Error。
```
class 語料表管理(ReadOnlyAdminFields, admin.ModelAdmin):
```

直接移除外掛即可。
```
class 校對表管理(admin.ModelAdmin):
```
