### ISSUE TITLE
欄位名

### ISSUE THREAD

**Issue by sih4sing5hong5** [i3thuan5/gi2_liau7_khoo3#44]
https://hackmd.io/c/ByyCcnsZb/https%3A%2F%2Fhackmd.io%2Fs%2FBkUHWO9FW%23
## 名詞
>[name=呂老師]
>漢字→臺語漢字
>口語調臺羅→口語臺羅

**Comment by sih4sing5hong5** [comment]
https://stackoverflow.com/a/8802119/3640653

**Comment by a8568730** [comment]
直接migrate就好了吧

**Comment by sih4sing5hong5** [comment]
應該免做矣
