### ISSUE TITLE
系統愛檢查漢字佮本調拼音

### ISSUE THREAD

**Issue by sih4sing5hong5** [i3thuan5/gi2_liau7_khoo3#9]
#####  漢字佮本調

結論：
save了，愛自動算，存佇資料庫

#####  資料
1. 現算
2. 囥語料表
3. 囥語料表1-1的表

##### 出現佇
- filter
- list_display
- field_set

**Comment by a8568730** [comment]
用`用字表`檢查是否字有用著

**Comment by a8568730** [comment]
完成矣
